### ISSUE TITLE
Suggestions on JOSS paper

### ISSUE THREAD

**Issue by thomakra** [KALMUS-Color-Toolkit/KALMUS#3]
Regarding the JOSS paper under review, here are some suggestions to improve the submission:

Please have a look at the references in the paper and make sure it is possible to find them online without too much effort by providing DOI's, URLs, etc.
When searching, I could not find anything resembling the Adams (2021) reference. Is it under review somewhere so that it is not available?

I notice that the main barcodes do not have axis labels. If I understand correctly, each pixel represents some statistic of the color of a single frame and these statistics are then ordered top-to-bottom, then left-to-right to form an image. I'm wondering if it would make it easier to get a feel for the length of a sequence if the x-axis ticks showed the total elapsed frames/seconds and the y-axis showed the frames/seconds per column with appropriate labels.

I think it would be nice to elaborate a little how the barcodes are generated. There is a very nice table [here](https://github.com/KALMUS-Color-Toolkit/KALMUS/blob/master/notebooks/USAGE_COMMAND_LINE_UI.md) giving an overview of the provided metrics and the types of region from which the metric is computed. Perhaps it would be nice to include it in the paper with a few lines describing it?

Other than that I think the paper looks nice and the package is well documented!

**Comment by yc015** [comment]
Hi @thomakra, thank you so much for your comments. We are updating the missing DOIs of the citation. For the Adams (2021) reference, the paper is still in progress and not being published yet. Therefore, we don't have a DOI corresponding to that article. Do you have any recommendations about addressing the Adams (2021) reference?

**Comment by yc015** [comment]
Hello @thomakra, here are some updates on your suggestions!

(1) For the DOIs and URLs, all the missing DOIs have been added to the paper except for the Adams (2021), which is still in progress. We wish to hear your suggestion about how to address this in-progress article.

(2) For the x-axis ticks and y-axis label, it would help a lot in direct comparison using the temporal ticks! I have just changed the main barcodes following your suggestion. Here is how it looks like now:

![main_barcode](https://user-images.githubusercontent.com/69224866/115161580-90bab780-a06c-11eb-95b8-9101902f00a9.png)

The y-label shows the seconds per column rate, and the x-axis ticks show the total elapsed time.

(3) For the [table](https://github.com/KALMUS-Color-Toolkit/KALMUS/blob/master/notebooks/USAGE_COMMAND_LINE_UI.md), we have included it in the paper with some descriptions of available metrics and types of region. Here is the link to the new article proof: [https://github.com/openjournals/joss-papers/blob/joss.03156/joss.03156/10.21105.joss.03156.pdf](https://github.com/openjournals/joss-papers/blob/joss.03156/joss.03156/10.21105.joss.03156.pdf).

Thank you again for these invaluable suggestions! We are looking forward to hearing your feedback.

**Comment by thomakra** [comment]
Thank you for your changes. I think it looks very good!

> Hi @thomakra, thank you so much for your comments. We are updating the missing DOIs of the citation. For the Adams (2021) reference, the paper is still in progress and not being published yet. Therefore, we don't have a DOI corresponding to that article. Do you have any recommendations about addressing the Adams (2021) reference?

Regarding the Adams 2021 submission: I think I would check with the editor if they have any recommendations from the journal's side. Since the reference is used as an example of use, perhaps it can be omitted. If the point for including it is to link the software paper with the other paper, perhaps the JOSS paper can be referenced in the Adams paper instead? I guess the course of action may be dictated by which paper gets accepted first. At the very least it should state the journal it has been submitted to and say something like "(submitted)" or "(in review)".

One final thing that puzzled me: The review issue in GitHub references "Version: v.1.3.5", however I can't see any tags in your repository. Where do you have these version numbers?

**Comment by yc015** [comment]
Hello @thomakra, thank you for your suggestions on Adams reference! I agree it may be more helpful to reference this paper in the Adams paper instead, and we would like to wait for the editor's recommendations.

For the versioning, we archived our package through PyPI. The Version: v.1.3.5 is corresponding to the package's 1.3.5 release on PyPI: [link to v1.3.5 on PyPI](https://pypi.org/project/kalmus/1.3.5/). 

After we submit the JOSS paper, the package has progressed to version: v1.3.8 in the past three months. [link to v1.3.8 on PyPI](https://pypi.org/project/kalmus/) Should we update the version number in our JOSS paper to reflect this change?

**Comment by thomakra** [comment]
Thanks for the clarification.
I guess I just expected the versions to be tags in the git repository.
No worries.

I have no further comments and I think you can safely close the issue and
wait for comments from the other reviewer.

**Comment by yc015** [comment]
Thank you again for reviewing our work! I will close this issue now.

**Comment by elektrobohemian** [comment]
in addition to the remarks made by @thomakra, I have some recommendations and a central question.

you are stating that color differences are subtle (p. 1) and that studies are also carried out on historical film releases (p. 3) which are most likely retro-digitized. thus, I was wondering why the whole paper is not addressing issues such as color spaces and gamut mapping. In case you deal with two retro-digitized film copies of the same movie your tool would create different color analyses just because of the fact that the digitizers used different devices and color profiles and decided to use different color spaces during processing -although the color difference is not present in the original material. (the same holds true for different editions with additional post-production runs or introduction of HDR or the like.) I would address this issue at least as a potential risk when using KALMUS. alternatively, you could add a warning to the tool itself or provide options to carry out gamut mappings if color profiles mismatch. the color profile issues of scanners etc. are definitely out of the scope of your paper. what has been digitized without care cannot be healed by your software, maybe you want to discuss this issue as you cannot control all the variables affecting color.

besides this conceptual issue, I have only minor hints on improving the readability of the text:

* (p. 2, l. 39) Be a little more precise why existing movie barcode software is inadequate.
* (p. 2, l. 42) "a barcode's data" is relatively vague, maybe you could give an example or refer to later parts of the paper.
* (p. 2, l. 44ff.) I would expand the list as a separate text block
* (p. 3, l. 53ff.) this could be a potential location to discuss the issue presented above

**Comment by yc015** [comment]
Hello @elektrobohemian! Sorry for my late reply. Other authors and I have carefully discussed your remarkable question of Gamut mapping last week.

We added a footnote of warning for analyzing films that are digitized with different color spaces in p. 3, l. 65.  

We also made the following changes to the text according to your hints:  
1. (p. 2, l. 40) We answer why existing barcode software is inadequate.
2. (p. 2, l. 43ff.) We Illustrate the "barcode's data".
3. (p. 2, l. 46ff.) Expand the lists.

The newly compiled paper can be downloaded here: [https://raw.githubusercontent.com/openjournals/joss-papers/joss.03156/joss.03156/10.21105.joss.03156.pdf](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03156/joss.03156/10.21105.joss.03156.pdf)

Thank you again for these remarkable suggestions! Please let us know if you have any following questions.

**Comment by elektrobohemian** [comment]
thanks for work. I have tested the software as well and couldn't find any issues. I recommend your interesting work for publication.

**Comment by yc015** [comment]
Thank you so much for reviewing our work! I will close this issue now.
